//! GF(2^8) arithmetic for RAID-6 Q-parity reconstruction.
//!
//! Mirrors the tables generated by `nonraid/raid6/mktables.c` (which itself
//! mirrors the Linux kernel's `raid6` implementation by H. Peter Anvin).
//! The field is GF(2^8) with the irreducible polynomial `x^8 + x^4 + x^3 +
//! x + 1`, encoded as `0x1d` (the low 8 bits of the reduction polynomial —
//! the implicit `x^8` bit is dropped).
//!
//! # The Q syndrome
//!
//! For a NonRAID/Unraid array with `n` data disks in slots `1..=n`, the
//! Q parity at every offset is
//!
//! ```text
//!   Q = XOR_{j=1..n} (g^(j-1) * D_j)
//! ```
//!
//! where `g = 2` is the generator (a primitive element of GF(2^8)), `D_j`
//! is the on-disk byte of data disk at slot `j`, and missing regions of
//! asymmetric (smaller) disks contribute `0` (the additive identity).
//! Multiplication and XOR are the field operations.
//!
//! This matches `nonraid/raid6/int.uc`'s `gen_syndrome`, which initialises
//! `wq = dptr[z0]` (z0 = highest data column) and walks downward applying
//! `wq = (wq * 2) ^ wd`.  Each step multiplies the running `wq` by `g`
//! *before* folding in the next-lower column, so the highest column
//! (`z = z0`) accumulates `z0` factors of `g` and the lowest column
//! (`z = 0`) accumulates none — i.e. the coefficient of column `z` is
//! `g^z`.  The NonRAID driver (`unraid.c` column mapping) places data
//! disks in slot order into `srcs[0..n-1]`, so column `i = slot-1` carries
//! coefficient `g^i = g^(slot-1)`.  This also matches `recov.c`'s
//! `raid6_datap_recov_intx1`, which uses `gfinv[gfexp[faila]]` as the
//! recovery multiplier for the failed column `faila` (0-based).
//!
//! # Recovering one missing data disk via Q
//!
//! Rearranging for the corrupt disk `D_k` (slot `k`, 1-based):
//!
//! ```text
//!   D_k = g^(-(k-1)) * (Q XOR XOR_{j!=k} (g^(j-1) * D_j))
//! ```
//!
//! (subtraction = XOR in GF(2^8); `g^(-a) = g^(255-a)` since `g^255 = 1`).
//! `g^(-(k-1))` is computed mod 255.  This is the single-failure case of
//! `raid6_datap_recov` / `raid6_2data_recov` from `nonraid/raid6/recov.c`,
//! specialised to one missing data disk and a known-good Q.
//!
//! # Performance note
//!
//! The kernel ships SIMD-accelerated variants (`raid6/recov_avx2.c`,
//! `recov_avx512.c`, `recov_neon.c`, …) for throughput on full-stripe
//! rebuilds.  For scrub-rs we recover one 4 KiB block at a time, so the
//! 64 KiB `gfmul` table below — a direct port of `mktables.c`'s
//! `nonraid_gfmul` — is more than fast enough: the I/O to read the other
//! disks dominates by ~10×.

/// Precomputed 256×256 multiplication table for GF(2^8) with poly 0x1d.
///
/// `gfmul[a][b] == a * b` in the field.  Direct port of `mktables.c`'s
/// `gfmul()` (Russian-peasant multiply: shift `a`, reduce by 0x1d when
/// the high bit escapes, add into accumulator when `b`'s low bit is set).
pub static GFMUL: [[u8; 256]; 256] = build_gfmul();

/// Powers of the generator `g = 2`: `GFEXP[e] == 2^e` in the field, for
/// `e in 0..255`.  Entry 255 is `0` (sentinel, since `2^255 == 1` would
/// alias entry 0).  Matches `nonraid_gfexp`.
pub static GFEXP: [u8; 256] = build_gfexp();

/// Multiplicative inverses in GF(2^8): `GFINV[x] == x^-1 == x^254` for
/// `x != 0`, and `GFINV[0] == 0` (undefined, kept zero for table
/// elegance).  Matches `nonraid_gfinv`.
pub static GFINV: [u8; 256] = build_gfinv();

/// `GFEXI[e] == GFINV[GFEXP[e] XOR 1]`, the `inv(g^e + 1)` table used by
/// `raid6_2data_recov_intx1` as the `pbmul` multiplier table for one of
/// the two failed columns.  Matches `nonraid_gfexi`.  Built from `GFINV`
/// and `GFEXP` at const-eval time.
pub static GFEXI: [u8; 256] = build_gfexi();

const fn gf_mul_scalar(mut a: u8, mut b: u8) -> u8 {
    let mut v: u8 = 0;
    while b != 0 {
        if b & 1 != 0 {
            v ^= a;
        }
        // a <- a * 2 in GF(2^8): shift left, reduce by 0x1d if high bit set.
        let hi = a & 0x80;
        a = (a << 1) ^ (if hi != 0 { 0x1d } else { 0 });
        b >>= 1;
    }
    v
}

const fn build_gfmul() -> [[u8; 256]; 256] {
    let mut t = [[0u8; 256]; 256];
    let mut a = 0;
    while a < 256 {
        let mut b = 0;
        while b < 256 {
            t[a][b] = gf_mul_scalar(a as u8, b as u8);
            b += 1;
        }
        a += 1;
    }
    t
}

const fn build_gfexp() -> [u8; 256] {
    let mut t = [0u8; 256];
    let mut v: u8 = 1;
    let mut i = 0;
    while i < 255 {
        t[i] = v;
        // v <- v * 2 in GF(2^8).
        let hi = v & 0x80;
        v = (v << 1) ^ (if hi != 0 { 0x1d } else { 0 });
        i += 1;
    }
    // Entry 255: 2^255 == 1, but we leave 0 to avoid aliasing entry 0
    // (matches mktables.c, which sets v=0 when v wraps to 1).
    t[255] = 0;
    t
}

/// x^-1 == x^254 in GF(2^8).  Const-eval helper for building GFINV.
/// Mirrors mktables.c's gfpow(x, 254) with repeated squaring.
const fn gf_pow_const(x: u8, mut p: u32) -> u8 {
    let mut v: u8 = 1;
    let mut a = x;
    while p > 0 {
        if p & 1 != 0 {
            v = gf_mul_scalar(v, a);
        }
        a = gf_mul_scalar(a, a);
        p >>= 1;
    }
    v
}

const fn build_gfinv() -> [u8; 256] {
    let mut t = [0u8; 256];
    let mut i = 0;
    while i < 256 {
        t[i] = if i == 0 { 0 } else { gf_pow_const(i as u8, 254) };
        i += 1;
    }
    t
}

const fn build_gfexi() -> [u8; 256] {
    // GFEXI[e] = GFINV[GFEXP[e] ^ 1].  Both GFINV and GFEXP are already
    // const-built, so this composes at compile time.
    let gfinv = build_gfinv();
    let gfexp = build_gfexp();
    let mut t = [0u8; 256];
    let mut i = 0;
    while i < 256 {
        t[i] = gfinv[(gfexp[i] ^ 1) as usize];
        i += 1;
    }
    t
}

/// `g^e` in GF(2^8), with the exponent taken mod 255 (so `g^255 == g^0`).
/// Negative exponents are handled by the caller via `gf_inv`.
pub fn gf_exp(e: i32) -> u8 {
    let e = e.rem_euclid(255);
    GFEXP[e as usize]
}

/// `g^(-e)` in GF(2^8), i.e. `GFINV[GFEXP[e mod 255]]`.  Convenience
/// wrapper used by the 2-disk solve for the `qmul` multiplier table.
pub fn gf_exp_inv(e: i32) -> u8 {
    let e = e.rem_euclid(255);
    GFINV[GFEXP[e as usize] as usize]
}

/// Multiplicative inverse `x^-1 = x^254` in GF(2^8).  Matches
/// `nonraid_gfinv`.  `gf_inv(0)` is undefined; returns 0.
#[allow(dead_code)]
pub fn gf_inv(x: u8) -> u8 {
    if x == 0 {
        return 0;
    }
    gf_pow(x, 254)
}

/// `x^p` in GF(2^8) via repeated squaring.  Mirrors `mktables.c`'s `gfpow`.
#[allow(dead_code)]
pub fn gf_pow(x: u8, mut p: i32) -> u8 {
    p %= 255;
    if p < 0 {
        p += 255;
    }
    let mut v: u8 = 1;
    let mut a = x;
    while p > 0 {
        if p & 1 != 0 {
            v = GFMUL[v as usize][a as usize];
        }
        a = GFMUL[a as usize][a as usize];
        p >>= 1;
    }
    v
}

/// Multiply two field elements via the precomputed table.
#[allow(dead_code)]
pub fn gf_mul(a: u8, b: u8) -> u8 {
    GFMUL[a as usize][b as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gfmul_table_is_consistent() {
        // g * 1 == g  and  g * 0 == 0 for all g.
        for g in 0..=255u8 {
            assert_eq!(gf_mul(g, 0), 0);
            assert_eq!(gf_mul(g, 1), g);
        }
    }

    #[test]
    fn gfexp_matches_double_and_reduce() {
        // GFEXP[e] must equal 2 multiplied by itself e times.
        let mut v: u8 = 1;
        for e in 0..255 {
            assert_eq!(GFEXP[e], v, "GFEXP[{e}]");
            let hi = v & 0x80;
            v = (v << 1) ^ (if hi != 0 { 0x1d } else { 0 });
        }
    }

    #[test]
    fn gf_inv_round_trip() {
        for x in 1..=255u8 {
            let inv = gf_inv(x);
            assert_ne!(inv, 0, "gf_inv({x}) = 0");
            assert_eq!(gf_mul(x, inv), 1, "gf_inv({x}) = {inv}");
        }
    }

    #[test]
    fn gf_exp_period_255() {
        // g^255 == g^0 == 1.
        assert_eq!(gf_exp(0), 1);
        assert_eq!(gf_exp(255), 1);
        assert_eq!(gf_exp(256), 2);
        assert_eq!(gf_exp(-1), gf_exp(254));
    }

    #[test]
    fn q_syndrome_matches_gen_syndrome_pattern() {
        // Reproduce int.uc's gen_syndrome for a 3-data-disk stripe and
        // cross-check against the closed-form Q = XOR g^(slot-1) * D_slot.
        let d: [u8; 3] = [0x11, 0x22, 0x80];
        let n = d.len(); // 3 data disks, slots 1..=3

        // gen_syndrome walk: wq = d[z0]; for z = z0-1..0: wq = (wq*2) ^ d[z].
        let z0 = n - 1;
        let mut wq: u8 = d[z0];
        for z in (0..z0).rev() {
            wq = gf_mul(wq, 2) ^ d[z];
        }

        // Closed form: Q = XOR_{j=1..n} g^(j-1) * D_j  (j is slot, D_j = d[j-1]).
        let mut q: u8 = 0;
        for j in 1..=n {
            q ^= gf_mul(gf_exp((j - 1) as i32), d[j - 1]);
        }
        assert_eq!(wq, q, "gen_syndrome walk vs closed-form Q");
    }

    #[test]
    fn recover_one_disk_via_q() {
        // 4 data disks.  Bake Q from the full set, then pretend disk at
        // slot k=2 is corrupt and reconstruct it from Q + the others.
        let d: [u8; 4] = [0x01, 0x02, 0x04, 0x08];
        let n = d.len();
        let mut q: u8 = 0;
        for j in 1..=n {
            q ^= gf_mul(gf_exp((j - 1) as i32), d[j - 1]);
        }
        let k = 2; // slot, 1-based
        let mut acc: u8 = q;
        for j in 1..=n {
            if j == k {
                continue;
            }
            acc ^= gf_mul(gf_exp((j - 1) as i32), d[j - 1]);
        }
        let recovered = gf_mul(gf_exp(-((k - 1) as i32)), acc);
        assert_eq!(recovered, d[k - 1]);
    }
}
