[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "btrfs-recon"
version = "0.1.0"
description = "BTRFS reconstruction and corruption analysis"
requires-python = ">=3.10"
dependencies = [
  "crc32c",
  "construct",
  "construct-typing",
  "intervaltree",
  "loguru"
]
